export enum AppErrorCode {
  AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
  AUTHORIZATION_DENIED = 'AUTHORIZATION_DENIED',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  ASSESSMENT_EXPIRED = 'ASSESSMENT_EXPIRED',
  ASSESSMENT_ACCESS_DENIED = 'ASSESSMENT_ACCESS_DENIED',
  AI_PROVIDER_ERROR = 'AI_PROVIDER_ERROR',
  AI_RATE_LIMITED = 'AI_RATE_LIMITED',
  QUEUE_ERROR = 'QUEUE_ERROR',
  DATABASE_ERROR = 'DATABASE_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  CONFLICT = 'CONFLICT',
  BAD_REQUEST = 'BAD_REQUEST',
  MAINTENANCE_MODE = 'MAINTENANCE_MODE'
}
