'use client';

import React, { useState, useEffect, useRef } from 'react';
import { AuthGuard } from '@/components/auth/AuthGuard';
import { DashboardLayout } from '@/components/layout/DashboardLayout';

interface ChatMessage {
  sender: 'USER' | 'AI';
  text: string;
  timestamp: string;
}

export default function StudentLearningPage() {
  const [activeStep, setActiveStep] = useState<number>(2); // Step 2 is active Division
  const [selectedPracticeAnswer, setSelectedPracticeAnswer] = useState<number | null>(null);
  const [isAnswerSubmitted, setIsAnswerSubmitted] = useState<boolean>(false);
  const [stepCompleted, setStepCompleted] = useState<boolean>(false);

  // AI Tutor Drawer State
  const [isAiDrawerOpen, setIsAiDrawerOpen] = useState<boolean>(true);
  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([
    {
      sender: 'AI',
      text: 'Hello! I am your AI Remedial Tutor. I am here to guide you through Division with Remainders step-by-step. What would you like help with?',
      timestamp: 'Just now',
    },
  ]);
  const [inputQuery, setInputQuery] = useState<string>('');
  const chatEndRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [chatMessages, isAiDrawerOpen]);

  const handleSendMessage = (textToSend?: string) => {
    const query = textToSend || inputQuery;
    if (!query.trim()) return;

    const formattedTime = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
    const newMsg: ChatMessage = { sender: 'USER', text: query.trim(), timestamp: formattedTime };
    setChatMessages((prev) => [...prev, newMsg]);
    if (!textToSend) setInputQuery('');

    // Intelligent pedagogical AI response routing
    setTimeout(() => {
      const qLower = query.toLowerCase().trim();
      let responseText = 'That is a great question! In long division, remember the 4 core steps: 1) Divide ➔ 2) Multiply ➔ 3) Subtract ➔ 4) Bring Down. Which step would you like to review?';

      if (/^(hi|hello|hey|greetings|good morning|good afternoon)/i.test(qLower)) {
        responseText = 'Hello there! How can I help you with your Division lesson today? Feel free to ask for a worked example, a practice hint, or concept explanation!';
      } else if (qLower.includes('example') || qLower.includes('sample')) {
        responseText = 'Let us look at 17 ÷ 3. 3 goes into 17 five times (3 × 5 = 15). 17 minus 15 leaves a remainder of 2!';
      } else if (qLower.includes('fraction') || qLower.includes('why')) {
        responseText = 'Division is the foundation of fractions because a fraction like 3/4 literally means 3 divided by 4!';
      } else if (qLower.includes('hint') || qLower.includes('practice') || qLower.includes('help')) {
        responseText = 'For the practice question below: 23 ÷ 4. Find the largest multiple of 4 that is less than or equal to 23 (4 × 5 = 20), then subtract to find the remainder!';
      }

      setChatMessages((prev) => [
        ...prev,
        { sender: 'AI', text: responseText, timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) },
      ]);
    }, 500);
  };

  const handleCheckAnswer = () => {
    if (selectedPracticeAnswer !== null) {
      setIsAnswerSubmitted(true);
      if (selectedPracticeAnswer === 1) { // Correct: Quotient 5, Remainder 3
        setStepCompleted(true);
      }
    }
  };

  return (
    <AuthGuard allowedRoles={['STUDENT']}>
      <DashboardLayout>
        <div className="space-y-6 max-w-5xl">
          {/* Header */}
          <div className="flex items-center justify-between">
            <div>
              <div className="flex items-center space-x-2">
                <span className="text-xl">🛣️</span>
                <h1 className="text-2xl font-bold text-white tracking-tight">Personalized Remediation Plan</h1>
              </div>
              <p className="text-sm text-slate-400 mt-1">
                Targeted prerequisite learning path generated by the AI Diagnostic Engine.
              </p>
            </div>
            <button
              onClick={() => setIsAiDrawerOpen(!isAiDrawerOpen)}
              className="px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-white font-bold text-xs rounded-xl transition flex items-center space-x-2 shadow-lg shadow-indigo-600/20"
            >
              <span>🤖</span>
              <span>{isAiDrawerOpen ? 'Hide AI Tutor' : 'Open AI Tutor Assistant'}</span>
            </button>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            {/* Left 2 Cols: Interactive Step-by-Step Player */}
            <div className={`${isAiDrawerOpen ? 'lg:col-span-2' : 'lg:col-span-3'} space-y-6 transition-all duration-300`}>
              {/* Stepper Navigation Cards */}
              <div className="space-y-3">
                {/* Step 1 */}
                <div
                  onClick={() => setActiveStep(1)}
                  className={`p-4 border rounded-xl flex items-center justify-between cursor-pointer transition ${
                    activeStep === 1
                      ? 'border-emerald-500 bg-emerald-950/20'
                      : 'border-slate-800 bg-slate-900/40 hover:bg-slate-800/40'
                  }`}
                >
                  <div className="flex items-center space-x-3">
                    <span className="w-8 h-8 rounded-full bg-emerald-500/20 text-emerald-300 font-bold text-xs flex items-center justify-center border border-emerald-500/30">
                      ✓
                    </span>
                    <div>
                      <span className="text-xs font-semibold text-emerald-400">Step 1 • Mastered</span>
                      <h4 className="text-sm font-bold text-white">Addition & Subtraction (MATH-ADD-01)</h4>
                    </div>
                  </div>
                  <span className="text-xs font-semibold text-emerald-400 px-3 py-1 bg-emerald-500/10 rounded-full border border-emerald-500/20">
                    100% Mastered
                  </span>
                </div>

                {/* Step 2 */}
                <div
                  onClick={() => setActiveStep(2)}
                  className={`p-4 border rounded-xl flex items-center justify-between cursor-pointer transition ${
                    activeStep === 2
                      ? 'border-indigo-500 bg-indigo-950/30 shadow-lg shadow-indigo-600/10'
                      : 'border-slate-800 bg-slate-900/40 hover:bg-slate-800/40'
                  }`}
                >
                  <div className="flex items-center space-x-3">
                    <span className="w-8 h-8 rounded-full bg-indigo-600 text-white font-bold text-xs flex items-center justify-center shadow-md">
                      2
                    </span>
                    <div>
                      <span className="text-xs font-semibold text-indigo-400">Step 2 • Active Remediation Lesson</span>
                      <h4 className="text-sm font-bold text-white">Division with Remainders (MATH-DIV-01)</h4>
                      <p className="text-xs text-slate-400">Root gap requirement prior to Fractions.</p>
                    </div>
                  </div>
                  <span className="text-xs font-bold text-indigo-300 px-3 py-1 bg-indigo-500/20 rounded-full border border-indigo-500/30">
                    In Progress
                  </span>
                </div>

                {/* Step 3 */}
                <div
                  className="p-4 border border-slate-800 bg-slate-900/20 rounded-xl flex items-center justify-between opacity-60 cursor-not-allowed"
                >
                  <div className="flex items-center space-x-3">
                    <span className="w-8 h-8 rounded-full bg-slate-800 text-slate-500 font-bold text-xs flex items-center justify-center border border-slate-700">
                      🔒
                    </span>
                    <div>
                      <span className="text-xs font-semibold text-slate-500">Step 3 • Locked Target</span>
                      <h4 className="text-sm font-bold text-slate-300">Fractions & Decimals (MATH-FRAC-01)</h4>
                    </div>
                  </div>
                  <span className="text-xs text-slate-500">Requires Step 2</span>
                </div>
              </div>

              {/* Active Step Content */}
              {activeStep === 2 && (
                <div className="p-6 border border-slate-800 bg-slate-900/80 rounded-2xl space-y-6">
                  <div className="border-b border-slate-800 pb-4">
                    <span className="px-2.5 py-0.5 bg-indigo-500/10 text-indigo-300 text-[11px] font-mono rounded border border-indigo-500/20">
                      CONCEPT: MATH-DIV-01
                    </span>
                    <h3 className="text-xl font-bold text-white mt-2">Remedial Lesson: Division with Remainders</h3>
                    <p className="text-xs text-slate-300 mt-1">
                      When a number cannot be divided equally, the leftover amount is called the <strong>Remainder</strong>.
                    </p>
                  </div>

                  {/* Worked Example */}
                  <div className="p-4 bg-slate-800/40 rounded-xl border border-slate-800 space-y-3">
                    <h4 className="text-xs font-bold text-indigo-400 uppercase tracking-wider">Worked Step-by-Step Example</h4>
                    <div className="text-sm font-medium text-white">Problem: Calculate 19 ÷ 4</div>
                    <ul className="text-xs text-slate-300 space-y-2 pl-4 list-disc">
                      <li><strong>Step 1:</strong> How many times does 4 fit into 19 without exceeding it? (4 × 4 = 16).</li>
                      <li><strong>Step 2:</strong> Subtract 16 from 19: 19 - 16 = <strong>3</strong>.</li>
                      <li><strong>Step 3:</strong> Result is <strong>Quotient 4, Remainder 3</strong> (written as 4 R3).</li>
                    </ul>
                  </div>

                  {/* Interactive Practice Question */}
                  <div className="p-5 border border-indigo-500/30 bg-indigo-950/20 rounded-xl space-y-4">
                    <div className="flex items-center justify-between">
                      <h4 className="text-sm font-bold text-white">Interactive Check: Solve 23 ÷ 4</h4>
                      <span className="text-[10px] text-indigo-300 bg-indigo-500/20 px-2 py-0.5 rounded border border-indigo-500/30">
                        Practice Check
                      </span>
                    </div>

                    <div className="space-y-2">
                      {[
                        { id: 0, text: 'Quotient: 5, Remainder: 2' },
                        { id: 1, text: 'Quotient: 5, Remainder: 3' },
                        { id: 2, text: 'Quotient: 4, Remainder: 3' },
                      ].map((opt) => (
                        <button
                          key={opt.id}
                          onClick={() => {
                            setSelectedPracticeAnswer(opt.id);
                            setIsAnswerSubmitted(false);
                          }}
                          className={`w-full text-left p-3 rounded-lg text-xs font-medium border transition ${
                            selectedPracticeAnswer === opt.id
                              ? 'bg-indigo-600/30 border-indigo-500 text-white'
                              : 'bg-slate-800/60 border-slate-700 text-slate-300 hover:bg-slate-800'
                          }`}
                        >
                          {opt.text}
                        </button>
                      ))}
                    </div>

                    <div className="flex justify-between items-center pt-2">
                      <button
                        onClick={handleCheckAnswer}
                        disabled={selectedPracticeAnswer === null}
                        className="px-4 py-2 bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 text-white rounded-lg text-xs font-bold transition"
                      >
                        Check Answer
                      </button>

                      {isAnswerSubmitted && (
                        <div className={`text-xs font-bold ${selectedPracticeAnswer === 1 ? 'text-emerald-400' : 'text-rose-400'}`}>
                          {selectedPracticeAnswer === 1 ? 'Correct! 4 × 5 = 20, 23 - 20 = 3 remainder.' : 'Incorrect. Try again or ask AI Tutor!'}
                        </div>
                      )}
                    </div>
                  </div>

                  {/* Completion Action */}
                  <div className="pt-2 flex items-center justify-between border-t border-slate-800">
                    <div className="text-xs text-slate-400">
                      {stepCompleted ? '✅ Mastery updated to 85%!' : 'Complete practice to unlock Step 3.'}
                    </div>
                    <button
                      onClick={() => setStepCompleted(true)}
                      disabled={stepCompleted}
                      className="px-5 py-2.5 bg-emerald-600 hover:bg-emerald-500 disabled:opacity-60 text-white font-bold text-xs rounded-xl transition shadow-md"
                    >
                      {stepCompleted ? 'Remediation Step Completed!' : 'Mark Step Complete'}
                    </button>
                  </div>
                </div>
              )}
            </div>

            {/* Right Col: AI Remediation Tutor Assistant Drawer */}
            {isAiDrawerOpen && (
              <div className="p-5 border border-slate-800 bg-slate-900/90 rounded-2xl flex flex-col h-[560px] justify-between transition-all">
              <div>
                <div className="flex items-center justify-between pb-3 border-b border-slate-800">
                  <div className="flex items-center space-x-2">
                    <span className="text-lg">🤖</span>
                    <h3 className="text-sm font-bold text-white">AI Remedial Tutor</h3>
                  </div>
                  <span className="w-2.5 h-2.5 bg-emerald-400 rounded-full animate-pulse"></span>
                </div>

                {/* Quick Prompts */}
                <div className="py-2.5 flex flex-wrap gap-1.5 text-[11px]">
                  <button
                    onClick={() => handleSendMessage('Can you show me an example?')}
                    className="px-2.5 py-1 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-full border border-slate-700 transition"
                  >
                    💡 Example
                  </button>
                  <button
                    onClick={() => handleSendMessage('Why do fractions need division?')}
                    className="px-2.5 py-1 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-full border border-slate-700 transition"
                  >
                    ❓ Why Fractions?
                  </button>
                  <button
                    onClick={() => handleSendMessage('Give me a hint for practice')}
                    className="px-2.5 py-1 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-full border border-slate-700 transition"
                  >
                    🎯 Practice Hint
                  </button>
                </div>

                {/* Messages Box */}
                <div className="space-y-3 overflow-y-auto max-h-[330px] pr-1.5 scrollbar-thin scrollbar-thumb-slate-800">
                  {chatMessages.map((msg, i) => (
                    <div
                      key={i}
                      className={`p-3 rounded-xl text-xs space-y-1 ${
                        msg.sender === 'USER'
                          ? 'bg-indigo-600/20 border border-indigo-500/30 text-indigo-100 ml-6'
                          : 'bg-slate-800/60 border border-slate-700 text-slate-200 mr-4'
                      }`}
                    >
                      <div className="flex justify-between items-center text-[10px] text-slate-400">
                        <span className="font-bold">{msg.sender === 'USER' ? 'You' : 'AI Tutor'}</span>
                        <span>{msg.timestamp}</span>
                      </div>
                      <p className="leading-relaxed">{msg.text}</p>
                    </div>
                  ))}
                  <div ref={chatEndRef} />
                </div>
              </div>

              {/* Chat Input */}
              <div className="pt-3 border-t border-slate-800 flex space-x-2">
                <input
                  type="text"
                  value={inputQuery}
                  onChange={(e) => setInputQuery(e.target.value)}
                  onKeyDown={(e) => e.key === 'Enter' && handleSendMessage()}
                  placeholder="Ask your AI Tutor..."
                  className="flex-1 bg-slate-800 border border-slate-700 text-white rounded-lg px-3 py-2 text-xs focus:outline-none focus:border-indigo-500"
                />
                <button
                  onClick={() => handleSendMessage()}
                  className="px-3 py-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg text-xs font-bold transition"
                >
                  Send
                </button>
              </div>
            </div>
            )}
          </div>
        </div>
      </DashboardLayout>
    </AuthGuard>
  );
}
